### ISSUE TITLE
Inquiry on homework 4 - Activity #2 - prompt 1

### ISSUE THREAD

**Issue by rasiimwe** [STAT545-UBC-students/hw04-rasiimwe#1]
@vincenzocoia 

Hello Dr. Coia,
In Activity #2, prompt 1 of homework 4,  there is a section of the question that reads:
**"Take advantage of this new data shape to scatterplot life expectancy for one country against that of another."**

I have failed to make useful deductions from [my plots](https://github.com/STAT545-UBC-students/hw04-rasiimwe/blob/master/hw04-rasiimwe_files/figure-html/unnamed-chunk-4-1.png)

From my understanding, scatter plots help to reveal the relationship or association between two variables. But now..... the countries are independent and they have different stories. It's hard to say that an increase in one country's life expectancy leads to an increase in another or vice versa. I am a bit in a fix on how to explain the correlation between the life expectancy of one country against another. In my [previous scatter plots](https://github.com/STAT545-UBC-students/hw03-rasiimwe/blob/master/hw03-rasiimwe_files/figure-markdown_github/continent_sniff-1.png), of life expectancy vs GDP per capita, the relationships and their meanings were more clear.

Kindly enlighten me on how to explain this correlation? Or is the question more focused on our ability to now create such plots given the reshaped tibbles than the actual meaning of the relationships we see between the variables? 

Many thanks
Rebecca

**Comment by vincenzocoia** [comment]
Your original plots with very few observations don't communicate much information -- this is fine, it's due to there being a deficit of data, not due to a poor plot design. This is the main message that should be communicated in your report.

**Comment by rasiimwe** [comment]
@vincenzocoia 

Thanks for clarifying this.
